version: 2
jobs:
  build:
    docker:
      - image: circleci/jdk8
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: cache-{{ checksum "build.gradle" }}

      - run: gradle build

      - store_artifacts:
                path: build/libs/*.jar

  deploy:
    docker:
      - image: circleci/jdk8
    steps:
      - run: gradle publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master